version: "3.8"
services: 
    sql-server-db:
        container_name: sql-server-db-test
        image: mcr.microsoft.com/mssql/server:2019-latest
        volumes: 
            - mssql_dv:/data/db
        # keeping port open for DEV from outside of container
        ports: 
            - "1433:1433"
        # load environment variables defined by DEV env file
        # expectation is that this is a DEV instance of a
        #       MS SQL Server for development exclusively
        # if for PRD, the PID can go into the called env file
        env_file: 
            - ./dev_mssql.env
    dash-app:
        build:
            context: ./
            dockerfile: Dockerfile
        # load environment variables defined by DEV env file
        env_file: 
            - ./dev_app_env_vars.env
        ports:
            - "8080:8080"
        # bind mount for development
        volumes: 
            - ./ :/project_code
        working_dir: /project_code/app
        tty: true
        stdin_open: true
        # auto seed DEV db with data
        # this output can be discovered from the Docker logs of the container
        command: >
            sh -c "
            if [ "$dev_container" = "$TRUE_COMPARE" ]; then 
            python helpers/seed_db/mssql_db_data_generator.py; else
            echo 'Using non-dev configuration: database was not seeded for development'; fi ;
            tail -f /dev/null"

# DEV db volume
volumes: 
    mssql_dv: